### ISSUE TITLE
tidevice wdaproxy start wda failed:because HTTPError: 404 Client Error:  Not Found Url : https://tool.appetizer.io/JinjunHan/iOSDeviceSupport/raw/master/iOSDeviceSupport/17.0.zip

### ISSUE THREAD

**Issue by HaoWShi** [alibaba/tidevice#350]
Developer：
MacBook Pro：MacOS Sonoma
Iphone 14 Pro: IOS 17.0.3
 
通过XCode安装WDA到Iphone后，使用tidevice启动WDA时，报错，找不到对应的IOSDeviceSupport

**Comment by codeskyblue** [comment]
duplicated with https://github.com/alibaba/tidevice/issues/337
