### ISSUE TITLE
【需求】tidevice最新版本不支持iOS17，请问什么时候可以支持

### ISSUE THREAD

**Issue by morningofowl** [alibaba/tidevice#356]

**Comment by zhuge1127** [comment]
+1

**Comment by mxpenghaha** [comment]
+1

**Comment by zhuge1127** [comment]
你好，邮件已收到，稍后处理！ 谢谢！                                                        ~诸革

**Comment by codeskyblue** [comment]
duplicated with https://github.com/alibaba/tidevice/issues/337

**Comment by zhuge1127** [comment]
你好，邮件已收到，稍后处理！ 谢谢！                                                        ~诸革
