### ISSUE TITLE
tidevices 啟動wda發生問題

### ISSUE THREAD

**Issue by Allensususu** [alibaba/tidevice#379]
想問下，我在啟動windows下 使用tidevice指令為tidevice --udid 00008020-000535R42640001C xctest -B com.facebook.WebDriverAgentRunner.corey2.xctrunner

Xcode 打包wda.ipa環境 : 15.0
Appium wda 是最新的內容
Iphone XR IOS16.6

本地點擊WDA啟動正常，不過使用tidevice 啟動發生以下錯誤，附上log
[tidevice.txt](https://github.com/alibaba/tidevice/files/14948205/tidevice.txt)

![image](https://github.com/alibaba/tidevice/assets/46346226/9e6c6359-e525-4919-818f-aefa1de8b724)

排查了一段時間卡住卡住，輸入後WDA會閃退，不能進行測試

**Comment by codeskyblue** [comment]
如果点击WDA可以启动的话，tidevice改用launch来启动就行了，不需要用xcuitest命令
