### ISSUE TITLE
遥控端执行w3c协议控制主控设备时耗时比较严重！！！！

### ISSUE THREAD

**Issue by jianghuihon** [alibaba/tidevice#383]
<img width="820" alt="image" src="https://github.com/alibaba/tidevice/assets/23332908/85c61c03-57db-4a10-a279-87c96f3a70e2">
我这边经过埋点打印这个上下的时间，发现时差有1秒多时间，能否可以优化下

**Comment by codeskyblue** [comment]
这个你得去wda的项目里面去提
